name: project_env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - h5py=3.7.0
  - pandas
  - matplotlib
  - seaborn
  - numpy
  - scikit-learn
  - pytorch
  - dash
  - pip

  - pip:
    - airbase
    - pycodestyle
    - scikeras
    - holidays
    - fastapi
    - uvicorn